# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".browser_at_settings", # <mod_init>
  "nat", # <function_kamplot>
  "resid", # <function_kamplot>
  "benef_type1", # <function_kamplot>
  "sex", # <function_kamplot>
  "marital_stat", # <function_kamplot>
  "age", # <function_kamplot>
  "monthly_pension", # <function_kamplot>
  "KamilaCluster", # <function_kamplot>
  "path_graphs", # <function_kamplot>
  "age_retire", # <function_kamplot>
  "aadr", # <function_kamplot>
  "aadr", # <fun_ggplot_hist2>
  "monthly_pension", # <fun_ggplot_hist2>
  "benef_type", # <fun_ggplot_hist2>
  "marital_stat", # <fun_ggplot_hist2>
  "nat", # <fun_ggplot_hist2>
  "resid", # <fun_ggplot_hist2>
  "sex", # <fun_ggplot_hist2>
  "cluster_id", # <fun_ggplot_hist2>
  "ln_aadr", # <fun_ggplot_hist2>
  "benef_type1", # <fun_ggplot_hist2>
  "variable", # <fun_ggplot_hist2>
  "value", # <fun_ggplot_hist2>
  "numb_clust", # <fun_ggplot_hist2>
  "path_graphs", # <fun_ggplot_hist2>
  NULL
))
