#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom caTools sample.split
#' @importFrom data.table fwrite
#' @importFrom DiagrammeR add_global_graph_attrs
#' @importFrom DiagrammeR create_edge_df
#' @importFrom DiagrammeR create_graph
#' @importFrom DiagrammeR create_node_df
#' @importFrom DiagrammeR render_graph
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr funs
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_all
#' @importFrom dplyr mutate_if
#' @importFrom dplyr n
#' @importFrom dplyr rename
#' @importFrom dplyr rename_if
#' @importFrom dplyr select
#' @importFrom fs dir_copy
#' @importFrom fs dir_create
#' @importFrom fst read_fst
#' @importFrom fst write_fst
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_discrete
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_light
#' @importFrom grid grid.layout
#' @importFrom grid grid.newpage
#' @importFrom grid pushViewport
#' @importFrom grid viewport
#' @importFrom Hmisc bystats
#' @importFrom Hmisc describe
#' @importFrom Hmisc label<-
#' @importFrom Hmisc latex
#' @importFrom kamila kamila
#' @importFrom shiny incProgress
#' @importFrom stats IQR
#' @importFrom stats median
#' @importFrom stats quantile
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stringr str_remove
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr gather
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr spread
#' @importFrom tidyselect any_of
#' @importFrom tidyselect one_of
#' @importFrom utils head
#' @importFrom utils installed.packages
#' @importFrom utils packageVersion
## usethis namespace: end
NULL
